### ISSUE TITLE
Getting IndexError When Run on Ubuntu

### ISSUE THREAD

**Issue by dezigna** [schwifty42069/pmg#12]
root@:-):~# python3 -m piptv_pmg.pmg -o /var/www/html/tv.m3u

Working some black magic..

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/piptv_pmg/pmg.py", line 108, in <module>
    main(sys.argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/piptv_pmg/pmg.py", line 101, in main
    mw.retrieve_new_token()
  File "/usr/local/lib/python3.6/dist-packages/piptv_pmg/pmg.py", line 54, in retrieve_new_token
    self.wms_auth_token.update({"wmsAuthSign": bsoup.text.split("file: \'")[1].split("\'")
IndexError: list index out of range

```

**Comment by dezigna** [comment]
Actually I realize the code needed updating because of changed auth scheme. Works fine now after running upgrade command.

Thanks!
