### ISSUE TITLE
 IndexError in Windows

### ISSUE THREAD

**Issue by dtxxuk** [schwifty42069/pmg#14]
Hey!

I'm just setting this up for the first time on Windows. I'm getting an Index error when creating the m3U. 

"IndexError: list index out of range"

Can anyone help?

**Comment by cammyrjones** [comment]
I'm also having this issue
Error Message Below;
PS C:\Users\Administrator> py.exe -m piptv_pmg.pmg -o "C:\User\Administrator\file.m3u"

Working some black magic..

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\piptv_pmg\pmg.py", line 108, in <module>
    main(sys.argv[1:])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\piptv_pmg\pmg.py", line 101, in main
    mw.retrieve_new_token()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\piptv_pmg\pmg.py", line 54, in retrieve_new_toke
n
    self.wms_auth_token.update({"wmsAuthSign": bsoup.text.split("file: \'")[1].split("\'")
IndexError: list index out of range
