### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by cammyrjones** [schwifty42069/pmg#15]
I am getting the error message below when running 'python -m piptv_pmg.pmg -o C:\temp\piptv.m3u'

PS C:\Users\Administrator\downloads> python -m piptv_pmg.pmg -o C:\temp\piptv.m3u

Working some black magic..

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\piptv_pmg\pmg.py", line 108, in <module>
    main(sys.argv[1:])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\piptv_pmg\pmg.py", line 101, in main
    mw.retrieve_new_token()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\piptv_pmg\pmg.py", line 54, in retrieve_new_token
    self.wms_auth_token.update({"wmsAuthSign": bsoup.text.split("file: \'")[1].split("\'")
IndexError: list index out of range

**Comment by cammyrjones** [comment]
I get this error in Ubuntu server and Windows server 2016 Standard
