### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [schwifty42069/pmg#16]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.2.0. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary piptv-pmg -w /tmp/ext piptv-pmg==0.2.0
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting piptv-pmg==0.2.0
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/175/f85bab08d4ce6/piptv_pmg-0.2.0.tar.gz (3.9 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-l2rjczhl/piptv-pmg/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-l2rjczhl/piptv-pmg/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-l2rjczhl/piptv-pmg/pip-egg-info
         cwd: /tmp/pip-wheel-l2rjczhl/piptv-pmg/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-l2rjczhl/piptv-pmg/setup.py", line 6, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by schwifty42069** [comment]
I appreciate you doing this, if I ever start maintaining this again I'll merge your PR immediately. 

Unfortunately, all of the entertainment related content scrapers I've written have fallen into a state of disrepair because the websites they scrape have started taking the job of protecting their content from bots very seriously, so I haven't taken the time to manually parse what is usually just a bunch of very prohibitive, obfuscated JS.

Thanks again!
