### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ATD555** [schwifty42069/pmg#18]
Getting the following error on Windows 10 running Python 3.8.5

```
Working some black magic..

Traceback (most recent call last):
  File "C:\Users\Austin\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Austin\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Austin\AppData\Local\Programs\Python\Python38\lib\site-packages\piptv_pmg\pmg.py", line 108, in <module>
    main(sys.argv[1:])
  File "C:\Users\Austin\AppData\Local\Programs\Python\Python38\lib\site-packages\piptv_pmg\pmg.py", line 101, in main
    mw.retrieve_new_token()
  File "C:\Users\Austin\AppData\Local\Programs\Python\Python38\lib\site-packages\piptv_pmg\pmg.py", line 54, in retrieve_new_token
    self.wms_auth_token.update({"wmsAuthSign": bsoup.text.split("file: \'")[1].split("\'")
IndexError: list index out of range
```

Just installed piptv_pmg using the commands in the ReadMe.

**Comment by dblitt** [comment]
This is also occurring for me on Debian 10.6, Python 3.7.3
