### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by nmercuro** [schwifty42069/pmg#22]
When I try to run this command, I get the following error: 

```
Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\lib\site-packages\piptv_pmg\pmg.py", line 108, in <module>
    main(sys.argv[1:])
  File "C:\Python38\lib\site-packages\piptv_pmg\pmg.py", line 101, in main
    mw.retrieve_new_token()
  File "C:\Python38\lib\site-packages\piptv_pmg\pmg.py", line 54, in retrieve_new_token
    self.wms_auth_token.update({"wmsAuthSign": bsoup.text.split("file: \'")[1].split("\'")
IndexError: list index out of range
```
Any ideas? I'd really like to get this working to integrate the m3u into plex.

**Comment by xkrypt0nx** [comment]
I have the same problem

**Comment by ashipaek0** [comment]
$ python3 -m pip install piptv_pmg
Collecting piptv_pmg
  Downloading piptv_pmg-0.2.0-py3-none-any.whl (5.0 kB)
Collecting beautifulsoup4==4.8.1
  Downloading beautifulsoup4-4.8.1-py3-none-any.whl (101 kB)
     |████████████████████████████████| 101 kB 239 kB/s 
Collecting requests==2.22.0
  Downloading requests-2.22.0-py2.py3-none-any.whl (57 kB)
     |████████████████████████████████| 57 kB 965 kB/s 
Collecting setuptools==41.2.0
  Downloading setuptools-41.2.0-py2.py3-none-any.whl (576 kB)
     |████████████████████████████████| 576 kB 517 kB/s 
Requirement already satisfied: soupsieve>=1.2 in /usr/local/lib/python3.9/dist-packages (from beautifulsoup4==4.8.1->piptv_pmg) (2.2.1)
Collecting chardet<3.1.0,>=3.0.2
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 1.1 MB/s 
Collecting idna<2.9,>=2.5
  Downloading idna-2.8-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 641 kB/s 
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
     |████████████████████████████████| 127 kB 387 kB/s 
Requirement already satisfied: certifi>=2017.4.17 in ./.local/lib/python3.9/site-packages (from requests==2.22.0->piptv_pmg) (2020.12.5)
Installing collected packages: urllib3, idna, chardet, setuptools, requests, beautifulsoup4, piptv-pmg
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.26.5
    Uninstalling urllib3-1.26.5:
      Successfully uninstalled urllib3-1.26.5
  Attempting uninstall: idna
    Found existing installation: idna 3.2
    Uninstalling idna-3.2:
      Successfully uninstalled idna-3.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
launchpadlib 1.10.13 requires testresources, which is not installed.
Successfully installed beautifulsoup4-4.8.1 chardet-3.0.4 idna-2.8 piptv-pmg-0.2.0 requests-2.22.0 setuptools-41.2.0 urllib3-1.25.11








:~$ python3 -m piptv_pmg.pmg -o /home/example.m3u
  
Working some black magic..

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ashipa/.local/lib/python3.9/site-packages/piptv_pmg/pmg.py", line 108, in <module>
    main(sys.argv[1:])
  File "/home/ashipa/.local/lib/python3.9/site-packages/piptv_pmg/pmg.py", line 101, in main
    mw.retrieve_new_token()
  File "/home/ashipa/.local/lib/python3.9/site-packages/piptv_pmg/pmg.py", line 54, in retrieve_new_token
    self.wms_auth_token.update({"wmsAuthSign": bsoup.text.split("file: \'")[1].split("\'")
IndexError: list index out of range
