### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by KingKoopa08** [schwifty42069/pmg#4]
First of all thanks for putting this together! I really appreciate it. I am running into this error when I run the script to get the m3u.

Trying to set environment variable for geckodriver

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/piptv_pmg/pmg.py", line 148, in <module>
    main(sys.argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/piptv_pmg/pmg.py", line 140, in main
    mw = M3UWriter(write_dir)
  File "/usr/local/lib/python3.6/dist-packages/piptv_pmg/pmg.py", line 55, in __init__
    self.driver = webdriver.Firefox(self.profile, options=self.options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by schwifty42069** [comment]
No problem!

Do you have a Firefox binary installed on your system? Sorry, that should have been included in the docs. I will add it whenever I have to patch/refactor something next.

**Comment by KingKoopa08** [comment]
I don't think I do. I will check that out. Thanks!

**Comment by KingKoopa08** [comment]
Hey man! Thank you so much! That worked, now may I ask how often the token refreshes? Should I need to run the script generate the m3u every day or hourly?

**Comment by schwifty42069** [comment]
Awesome glad to hear it man! The tokens are good for 6 hours, so I would set it up to run every 4 or 5! Enjoy brotha!
